// Server-only caption utilities (uses yt-dlp CLI)
import { execSync } from "child_process"
import { existsSync } from "fs"
import { join } from "path"
import type { CaptionTrack } from "./caption"

function getYtDlpPath(): string {
  const paths = [
    join(process.env.HOME || "", ".local/bin/yt-dlp"),
    "/usr/local/bin/yt-dlp",
    "/opt/homebrew/bin/yt-dlp",
    "yt-dlp",
  ]
  for (const p of paths) {
    if (p === "yt-dlp" || existsSync(p)) return p
  }
  return "yt-dlp"
}

const YT_DLP_PATH = getYtDlpPath()

export async function getCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const url = `https://www.youtube.com/watch?v=${videoId}`

  try {
    const output = execSync([YT_DLP_PATH, "--no-warnings", "--no-playlist", "-j", url].join(" "), {
      encoding: "utf-8",
      maxBuffer: 50 * 1024 * 1024,
    })

    const info = JSON.parse(output)
    const subtitles = info.subtitles || {}
    const automaticCaptions = info.automatic_captions || {}

    const tracks: CaptionTrack[] = []

    // Manual subtitles
    for (const [langCode, formats] of Object.entries(subtitles)) {
      const vttFormat = (formats as any[]).find((f) => f.ext === "vtt" || f.ext === "srv3")
      if (vttFormat) {
        tracks.push({
          languageCode: langCode,
          languageName: vttFormat.name || langCode,
          isAutoGenerated: false,
          baseUrl: vttFormat.url,
        })
      }
    }

    // Auto-generated captions
    for (const [langCode, formats] of Object.entries(automaticCaptions)) {
      const vttFormat = (formats as any[]).find((f) => f.ext === "vtt" || f.ext === "srv3")
      if (vttFormat) {
        tracks.push({
          languageCode: langCode,
          languageName: vttFormat.name || langCode,
          isAutoGenerated: true,
          baseUrl: vttFormat.url,
        })
      }
    }

    return tracks
  } catch (error) {
    console.error("Failed to get caption tracks:", error)
    return []
  }
}

export async function fetchCaptionXml(baseUrl: string): Promise<string> {
  const response = await fetch(baseUrl)
  if (!response.ok) {
    throw new Error("Failed to fetch captions")
  }
  return response.text()
}
