"use client"

import { useState, useCallback } from "react"
import { UrlInput } from "@/components/url-input"
import { CaptionWithVideo } from "@/components/caption-with-video"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Select } from "@/components/ui/select"
import type { CaptionTrack, CaptionEntry, CaptionFormat } from "@/lib/caption"
import { CAPTION_FORMATS, pickPreferredTrack } from "@/lib/caption"

function trackValue(track: CaptionTrack): string {
  return `${track.languageCode}:${track.isAutoGenerated ? "auto" : "manual"}`
}

function trackFromValue(tracks: CaptionTrack[], value: string): CaptionTrack | null {
  const [langCode, kind] = value.split(":")
  return tracks.find((t) => t.languageCode === langCode && (kind === "auto") === t.isAutoGenerated) ?? null
}

export default function CaptionPage() {
  const [videoId, setVideoId] = useState<string | null>(null)
  const [tracks, setTracks] = useState<CaptionTrack[]>([])
  const [selectedTrack, setSelectedTrack] = useState<CaptionTrack | null>(null)
  const [captionEntries, setCaptionEntries] = useState<CaptionEntry[]>([])
  const [selectedFormat, setSelectedFormat] = useState<CaptionFormat>("srt")
  const [isLoading, setIsLoading] = useState(false)
  const [isLoadingPreview, setIsLoadingPreview] = useState(false)
  const [isDownloading, setIsDownloading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchTracks = useCallback(async (id: string) => {
    setIsLoading(true)
    setError(null)
    setVideoId(id)
    setTracks([])
    setSelectedTrack(null)
    setCaptionEntries([])

    try {
      const response = await fetch(`/api/caption/list?videoId=${id}`)
      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || "Failed to fetch captions")
      }
      const data = await response.json()

      if (data.tracks.length === 0) {
        setError("No captions available for this video")
        return
      }

      setTracks(data.tracks)
      const preferred = pickPreferredTrack(data.tracks)
      setSelectedTrack(preferred)
      // Load caption preview in background (don't block UI)
      loadCaptionPreview(id, preferred)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong")
    } finally {
      setIsLoading(false)
    }
  }, [])

  const loadCaptionPreview = useCallback(async (id: string, track: CaptionTrack) => {
    setIsLoadingPreview(true)
    try {
      const response = await fetch(
        `/api/caption/preview?videoId=${encodeURIComponent(id)}&lang=${encodeURIComponent(track.languageCode)}`
      )
      if (!response.ok) throw new Error("Failed to load preview")
      const data = await response.json()
      setCaptionEntries(data.entries)
    } catch (err) {
      console.error("Preview error:", err)
    } finally {
      setIsLoadingPreview(false)
    }
  }, [])

  const handleTrackChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => {
      const track = videoId ? trackFromValue(tracks, e.target.value) : null
      if (track && videoId) {
        setSelectedTrack(track)
        loadCaptionPreview(videoId, track)
      }
    },
    [videoId, tracks, loadCaptionPreview]
  )

  const handleFormatChange = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectedFormat(e.target.value as CaptionFormat)
  }, [])

  const handleDownload = useCallback(async () => {
    if (!videoId || !selectedTrack) return

    setIsDownloading(true)
    try {
      const response = await fetch(
        `/api/caption/download?videoId=${encodeURIComponent(videoId)}&lang=${encodeURIComponent(selectedTrack.languageCode)}&format=${selectedFormat}`
      )

      if (!response.ok) throw new Error("Download failed")

      const blob = await response.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `${videoId}_${selectedTrack.languageCode}.${selectedFormat}`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error("Download failed:", err)
    } finally {
      setIsDownloading(false)
    }
  }, [videoId, selectedTrack, selectedFormat])

  return (
    <div className="py-12 px-4">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold text-text-primary">Caption Downloader</h1>
          <p className="text-text-secondary">
            Download YouTube captions and subtitles in multiple formats
          </p>
        </div>

        {/* Input Section */}
        <Card>
          <CardHeader>
            <CardTitle>Enter YouTube URL</CardTitle>
            <CardDescription>
              Paste a YouTube video URL to see available captions
            </CardDescription>
          </CardHeader>
          <CardContent>
            <UrlInput onSubmit={fetchTracks} isLoading={isLoading} />
          </CardContent>
        </Card>

        {/* Error */}
        {error && (
          <Card className="border-error/50 bg-error/5">
            <CardContent className="py-4">
              <p className="text-error text-sm">{error}</p>
            </CardContent>
          </Card>
        )}

         {/* Language + Format + Download (one card, show when we have tracks or loading) */}
         {(videoId && (tracks.length > 0 || isLoading)) && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle>Export</CardTitle>
              <CardDescription>
                Choose language and format, then download
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col sm:flex-row gap-4 items-stretch sm:items-end">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 flex-1">
                  <div className="space-y-1.5">
                    <label htmlFor="caption-lang" className="text-sm font-medium text-text-primary">
                      Language
                    </label>
                    <Select
                      id="caption-lang"
                      value={selectedTrack ? trackValue(selectedTrack) : ""}
                      onChange={handleTrackChange}
                      disabled={isLoading || tracks.length === 0}
                    >
                      <option value="">
                        {isLoading ? "Loading..." : tracks.length === 0 ? "No tracks" : "Select language"}
                      </option>
                      {tracks.map((track) => (
                        <option key={trackValue(track)} value={trackValue(track)}>
                          {track.languageName}
                          {track.isAutoGenerated ? " (auto)" : ""}
                        </option>
                      ))}
                    </Select>
                  </div>
                  <div className="space-y-1.5">
                    <label htmlFor="caption-format" className="text-sm font-medium text-text-primary">
                      Format
                    </label>
                    <Select
                      id="caption-format"
                      value={selectedFormat}
                      onChange={handleFormatChange}
                      disabled={!selectedTrack}
                    >
                      {CAPTION_FORMATS.map((format) => (
                        <option key={format} value={format}>
                          {format.toUpperCase()}
                        </option>
                      ))}
                    </Select>
                  </div>
                </div>
                <Button
                  onClick={handleDownload}
                  isLoading={isDownloading}
                  disabled={!selectedTrack}
                  className="w-full sm:w-auto shrink-0"
                >
                  <DownloadIcon className="w-4 h-4 mr-1.5" />
                  Download
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Video + transcript (show as soon as we have videoId; load in background) */}
        {videoId && (
          <CaptionWithVideo key={videoId} videoId={videoId} entries={captionEntries} />
        )}

       
      </div>
    </div>
  )
}

function DownloadIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}
