"use client"

import { useState, useCallback } from "react"
import { UrlInput } from "@/components/url-input"
import { CaptionPreview } from "@/components/caption-preview"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import type { CaptionTrack, CaptionEntry, CaptionFormat } from "@/lib/caption"
import { CAPTION_FORMATS } from "@/lib/caption"

export default function CaptionPage() {
  const [videoId, setVideoId] = useState<string | null>(null)
  const [tracks, setTracks] = useState<CaptionTrack[]>([])
  const [selectedTrack, setSelectedTrack] = useState<CaptionTrack | null>(null)
  const [captionEntries, setCaptionEntries] = useState<CaptionEntry[]>([])
  const [selectedFormat, setSelectedFormat] = useState<CaptionFormat>("srt")
  const [isLoading, setIsLoading] = useState(false)
  const [isLoadingPreview, setIsLoadingPreview] = useState(false)
  const [isDownloading, setIsDownloading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchTracks = useCallback(async (id: string) => {
    setIsLoading(true)
    setError(null)
    setVideoId(id)
    setTracks([])
    setSelectedTrack(null)
    setCaptionEntries([])

    try {
      const response = await fetch(`/api/caption/list?videoId=${id}`)
      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || "Failed to fetch captions")
      }
      const data = await response.json()
      
      if (data.tracks.length === 0) {
        setError("No captions available for this video")
        return
      }
      
      setTracks(data.tracks)
      // Auto-select first track
      setSelectedTrack(data.tracks[0])
      await loadCaptionPreview(data.tracks[0])
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong")
    } finally {
      setIsLoading(false)
    }
  }, [])

  const loadCaptionPreview = async (track: CaptionTrack) => {
    setIsLoadingPreview(true)
    try {
      const response = await fetch(
        `/api/caption/preview?url=${encodeURIComponent(track.baseUrl)}`
      )
      if (!response.ok) throw new Error("Failed to load preview")
      const data = await response.json()
      setCaptionEntries(data.entries)
    } catch (err) {
      console.error("Preview error:", err)
    } finally {
      setIsLoadingPreview(false)
    }
  }

  const handleTrackSelect = async (track: CaptionTrack) => {
    setSelectedTrack(track)
    await loadCaptionPreview(track)
  }

  const handleDownload = useCallback(async () => {
    if (!videoId || !selectedTrack) return

    setIsDownloading(true)
    try {
      const response = await fetch(
        `/api/caption/download?url=${encodeURIComponent(
          selectedTrack.baseUrl
        )}&format=${selectedFormat}&videoId=${videoId}&lang=${selectedTrack.languageCode}`
      )

      if (!response.ok) throw new Error("Download failed")

      const blob = await response.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `${videoId}_${selectedTrack.languageCode}.${selectedFormat}`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error("Download failed:", err)
    } finally {
      setIsDownloading(false)
    }
  }, [videoId, selectedTrack, selectedFormat])

  // Separate manual and auto-generated tracks
  const manualTracks = tracks.filter((t) => !t.isAutoGenerated)
  const autoTracks = tracks.filter((t) => t.isAutoGenerated)

  return (
    <div className="py-12 px-4">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold text-text-primary">Caption Downloader</h1>
          <p className="text-text-secondary">
            Download YouTube captions and subtitles in multiple formats
          </p>
        </div>

        {/* Input Section */}
        <Card>
          <CardHeader>
            <CardTitle>Enter YouTube URL</CardTitle>
            <CardDescription>
              Paste a YouTube video URL to see available captions
            </CardDescription>
          </CardHeader>
          <CardContent>
            <UrlInput onSubmit={fetchTracks} isLoading={isLoading} />
          </CardContent>
        </Card>

        {/* Error */}
        {error && (
          <Card className="border-error/50 bg-error/5">
            <CardContent className="py-4">
              <p className="text-error text-sm">{error}</p>
            </CardContent>
          </Card>
        )}

        {/* Track Selection */}
        {tracks.length > 0 && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle>Select Language</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Manual tracks */}
              {manualTracks.length > 0 && (
                <div>
                  <p className="text-sm font-medium text-text-secondary mb-2">
                    Manual Captions
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {manualTracks.map((track) => (
                      <button
                        key={`${track.languageCode}-manual`}
                        onClick={() => handleTrackSelect(track)}
                        className={cn(
                          "px-3 py-1.5 rounded-[6px] text-sm font-medium border",
                          selectedTrack?.languageCode === track.languageCode &&
                            !selectedTrack?.isAutoGenerated
                            ? "bg-primary text-white border-primary"
                            : "bg-surface text-text-primary border-border hover:border-primary/50"
                        )}
                      >
                        {track.languageName}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* Auto-generated tracks */}
              {autoTracks.length > 0 && (
                <div>
                  <p className="text-sm font-medium text-text-secondary mb-2">
                    Auto-generated
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {autoTracks.map((track) => (
                      <button
                        key={`${track.languageCode}-auto`}
                        onClick={() => handleTrackSelect(track)}
                        className={cn(
                          "px-3 py-1.5 rounded-[6px] text-sm font-medium border",
                          selectedTrack?.languageCode === track.languageCode &&
                            selectedTrack?.isAutoGenerated
                            ? "bg-primary text-white border-primary"
                            : "bg-surface text-text-primary border-border hover:border-primary/50"
                        )}
                      >
                        {track.languageName}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Format Selection & Download */}
        {selectedTrack && (
          <Card>
            <CardHeader className="pb-3">
              <CardTitle>Export Format</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col sm:flex-row gap-4 items-start sm:items-center justify-between">
                <div className="flex gap-2">
                  {CAPTION_FORMATS.map((format) => (
                    <button
                      key={format}
                      onClick={() => setSelectedFormat(format)}
                      className={cn(
                        "px-4 py-2 rounded-[6px] text-sm font-medium uppercase border",
                        selectedFormat === format
                          ? "bg-primary text-white border-primary"
                          : "bg-surface text-text-primary border-border hover:border-primary/50"
                      )}
                    >
                      {format}
                    </button>
                  ))}
                </div>
                <Button
                  onClick={handleDownload}
                  isLoading={isDownloading}
                  className="w-full sm:w-auto"
                >
                  <DownloadIcon className="w-4 h-4 mr-1.5" />
                  Download {selectedFormat.toUpperCase()}
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Preview */}
        {captionEntries.length > 0 && !isLoadingPreview && (
          <CaptionPreview entries={captionEntries} />
        )}

        {isLoadingPreview && (
          <Card>
            <CardContent className="py-8">
              <p className="text-center text-text-secondary">Loading preview...</p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  )
}

function DownloadIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}
